/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Author: Sandeep Agarwal (https://sketchfab.com/Sandeep7487)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/blender-icon-24b2a99ea2e2493695907c5aafe1fb5e
Title: Blender Icon
*/
import {Float, useGLTF} from '@react-three/drei'

const BlenderIcon = (props) => {
    const { nodes, materials } = useGLTF('/models/blender_icon.glb')
    return (
        <Float floatIntensity={1}>
            <group {...props} dispose={null}>
                <group rotation={[-0.04, -0.107, 0.091]} scale={0.25}>
                    <mesh
                        geometry={nodes.Plane_Material001_0.geometry}
                        material={materials['Material.001']}
                    />
                    <mesh
                        geometry={nodes.Plane_Material_0.geometry}
                        material={materials.Material}
                    />
                </group>
            </group>
        </Float>
    )
}

useGLTF.preload('/models/blender_icon.glb')

export default BlenderIcon