/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Author: AntonioModer (https://sketchfab.com/AntonioModer)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/unity-logo-3d-mesh-2afd04b26ca64c6b8392f75e217ffdb9
Title: Unity logo 3D mesh
*/
import {Float, useGLTF} from '@react-three/drei'

const UnityLogo = (props) => {
    const { nodes, materials } = useGLTF('/models/unity_logo_3d_mesh.glb')
    return (
        <Float floatIntensity={1}>
            <group scale={2} {...props} dispose={null}>
                <mesh
                    geometry={nodes.Unity_3DLogo_Material_0.geometry}
                    material={materials.Material}
                    position={[-1, 0.079, 0.181]}
                    rotation={[-Math.PI / 5, 5, 0]}
                    scale={[0.39, 0.39, 0.5]}
                />
            </group>
        </Float>
    )
}

useGLTF.preload('/models/unity_logo_3d_mesh.glb')

export default UnityLogo
