/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Author: noahwus (https://sketchfab.com/noahwus)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/unreal-engine-logo-e2e8f594095e41beb8d3f38783ab4706
Title: Unreal Engine Logo
*/
import {Float, useGLTF} from '@react-three/drei'

const UnrealLogo = (props) => {
    const { nodes, materials } = useGLTF('/models/unreal_engine_logo.glb')

    return (
        <Float floatIntensity={1}>
            <group  scale={0.006} {...props} dispose={null}>
                <mesh
                    geometry={nodes.Cube_Material_0.geometry}
                    material={materials.Material}
                    rotation={[-Math.PI / 2, 0, 0]}
                    scale={100}
                />
                <mesh
                    geometry={nodes.Cylinder_Material_0.geometry}
                    material={materials.Material}
                    rotation={[-Math.PI / 2, 0, 0]}
                    scale={100}
                />
            </group>
        </Float>
    )
}

useGLTF.preload('/models/unreal_engine_logo.glb')

export default UnrealLogo
